# Generated by Django 5.1.1 on 2024-09-24 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lesson", "0003_educationterm_lessonprogram_teachers_and_more"),
        ("student_info", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="education_term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lesson.educationterm",
            ),
        ),
    ]
