# Generated by Django 5.1.1 on 2024-09-24 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lesson", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name="lessonprogram",
            name="teachers",
            field=models.ManyToManyField(
                related_name="lesson_programs", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="education_term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lesson.educationterm",
            ),
        ),
        migrations.AddField(
            model_name="lessonprogram",
            name="education_term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lesson.educationterm",
            ),
        ),
    ]
