# Generated by Django 5.1.1 on 2024-09-25 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meet_name", models.CharField(max_length=255)),
                ("meet_date", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True, related_name="meetings", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
